### ISSUE TITLE
Double Posting

### ISSUE THREAD

**Issue by 2xCmet** [sufficiency/ribomic#1]
Your bot is posting the same text multiple times in the same Thread.
![unbenannt](https://cloud.githubusercontent.com/assets/17165042/23795371/92a0e180-0595-11e7-9faf-165dff36da93.PNG)

**Comment by sufficiency** [comment]
Definitely seems to be a problem. I will take a look tonight.

**Comment by sufficiency** [comment]
Should be fixed with https://github.com/sufficiency/ribomic/commit/72d40c0ca9743a02950f2f32c6005a8cb17c7358

**Comment by sufficiency** [comment]
Seems fine now. I am going to close this.

Thanks for the report.
